[package]
name = "advent-of-code"
version = "0.1.0"
authors = ["Calum Leslie <calumleslie@gmail.com>"]
edition = "2018"

[dependencies]
itertools = "0.8.0"
chrono = "0.4"
regex = "1"
lazy_static = "1.2.0"

[profile.release]
debug = true